version: '3'
services:
  test-react-app:
    container_name: test-react-app
    build:
      context: ./.docker/web
      dockerfile: Dockerfile
    environment:
      PORT: '3000'
      HOST: '0.0.0.0'
    ports:
      - 3000:3000
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    restart: always
